server:
  port: 8443
  contextPath: /firstSpring
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: springboot
    key-store-type: PKCS12
    key-alias: tomcat
spring:
    datasource:
      password: root
      url: jdbc:mysql://localhost:3306/univoq?user=root